-- Rollback: 20260929010000_default_catalog_seed.down.sql
-- Restores pre-migration M8 state (D-P7b-3)

WITH csv_rows(name) AS (
  VALUES
    ('45 Degree Back Extension'),
    ('Bicep cable pull'),
    ('Cable Lateral Raises'),
    ('Dips'),
    ('Dragon Flag'),
    ('Dumbbell Lateral Raises'),
    ('Face Pulls'),
    ('Incline Bench Press'),
    ('Inclined Bicep Curl'),
    ('L2H Cable Fly'),
    ('Lat Cable Prayer'),
    ('Lat Pull Down'),
    ('Leg Curl'),
    ('Leg Extension Machine'),
    ('Leg Raise'),
    ('Overhead Tricep Cable Pull'),
    ('Preacher Curl'),
    ('Rear delt crossover'),
    ('Reverse crunch'),
    ('Seated Cable Row'),
    ('Seated Chest Press'),
    ('Tricep Cable Pushdown'),
    ('Weighted Sit-Up'),
    ('Bench Press'),
    ('Romanian Deadlift'),
    ('Zercher Squat'),
    ('Overhead Press'),
    ('Barbell Back Squat'),
    ('Barbell Front Squat'),
    ('Barbell Box Squat'),
    ('Barbell Deadlift'),
    ('Barbell Sumo Deadlift'),
    ('Barbell Bent Over Row'),
    ('Pendlay Row'),
    ('Yates Row'),
    ('T-Bar Row'),
    ('Decline Bench Press'),
    ('Close Grip Bench Press'),
    ('Floor Press'),
    ('Push Press'),
    ('Behind The Neck Press'),
    ('Barbell Upright Row'),
    ('Barbell Shrug'),
    ('Barbell Hip Thrust'),
    ('Barbell Good Morning'),
    ('Barbell Walking Lunge'),
    ('Barbell Split Squat'),
    ('Barbell Hack Squat'),
    ('Barbell Standing Calf Raise'),
    ('Barbell Bicep Curl'),
    ('EZ Bar Bicep Curl'),
    ('Barbell Reverse Curl'),
    ('Barbell Spider Curl'),
    ('Barbell Skull Crusher'),
    ('Overhead Barbell Tricep Extension'),
    ('JM Press'),
    ('Barbell Landmine Press'),
    ('Barbell Landmine Twist'),
    ('Barbell Clean And Jerk'),
    ('Barbell Snatch'),
    ('Barbell Power Clean'),
    ('Trap Bar Deadlift'),
    ('Trap Bar Farmers Walk'),
    ('Dumbbell Bench Press'),
    ('Incline Dumbbell Press'),
    ('Decline Dumbbell Press'),
    ('Dumbbell Chest Fly'),
    ('Incline Dumbbell Fly'),
    ('One Arm Dumbbell Row'),
    ('Chest Supported Dumbbell Row'),
    ('Dumbbell Pullover'),
    ('Dumbbell Shrug'),
    ('Dumbbell Romanian Deadlift'),
    ('Dumbbell Goblet Squat'),
    ('Dumbbell Bulgarian Split Squat'),
    ('Dumbbell Walking Lunge'),
    ('Dumbbell Step-Up'),
    ('Dumbbell Standing Calf Raise'),
    ('Dumbbell Sumo Squat'),
    ('Seated Dumbbell Shoulder Press'),
    ('Arnold Press'),
    ('Standing Dumbbell Shoulder Press'),
    ('Dumbbell Front Raise'),
    ('Dumbbell Rear Delt Fly'),
    ('Dumbbell Upright Row'),
    ('Incline Dumbbell Rear Delt Raise'),
    ('Dumbbell Bicep Curl'),
    ('Dumbbell Hammer Curl'),
    ('Dumbbell Concentration Curl'),
    ('Dumbbell Spider Curl'),
    ('Zottman Curl'),
    ('Cross Body Hammer Curl'),
    ('Overhead Dumbbell Tricep Extension'),
    ('Dumbbell Skull Crusher'),
    ('Single Arm Dumbbell Tricep Extension'),
    ('Dumbbell Tricep Kickback'),
    ('Dumbbell Side Bend'),
    ('Dumbbell Snatch'),
    ('Dumbbell Thruster'),
    ('Dumbbell Clean And Press'),
    ('Dumbbell Farmers Carry'),
    ('Dumbbell Floor Press'),
    ('Cable Crossover Fly'),
    ('High To Low Cable Fly'),
    ('Standing Cable Chest Press'),
    ('Single Arm Cable Row'),
    ('Close Grip Cable Row'),
    ('Single Arm Cable Lateral Raise'),
    ('Cable Front Raise'),
    ('Cable Upright Row'),
    ('Cable Hammer Curl'),
    ('High Cable Bicep Curl'),
    ('Cable Tricep Kickback'),
    ('Cable Crunch'),
    ('Cable Pull Through'),
    ('Incline Chest Press Machine'),
    ('Decline Chest Press Machine'),
    ('Pec Deck Fly'),
    ('Machine Chest Fly'),
    ('Chest Supported Row Machine'),
    ('Seated Machine Row'),
    ('Iso-Lateral High Row Machine'),
    ('Assisted Pull-Up Machine'),
    ('Assisted Dip Machine'),
    ('Machine Shrug'),
    ('Leg Press Machine'),
    ('Hack Squat Machine'),
    ('Pendulum Squat Machine'),
    ('Belt Squat Machine'),
    ('Seated Calf Raise Machine'),
    ('Standing Calf Raise Machine'),
    ('Hip Abduction Machine'),
    ('Hip Adduction Machine'),
    ('Overhead Shoulder Press Machine'),
    ('Lateral Raise Machine'),
    ('Reverse Pec Deck Machine'),
    ('Bicep Curl Machine'),
    ('Tricep Extension Machine'),
    ('Abdominal Crunch Machine'),
    ('Reverse Hyperextension Machine'),
    ('Treadmill Running'),
    ('Stationary Bike'),
    ('Rowing Machine'),
    ('Stair Climber'),
    ('Elliptical Trainer'),
    ('SkiErg'),
    ('Assault Bike'),
    ('Rotary Torso Machine'),
    ('Sissy Squat Machine'),
    ('Push-Up'),
    ('Diamond Push-Up'),
    ('Decline Push-Up'),
    ('Incline Push-Up'),
    ('Pull-Up'),
    ('Chin-Up'),
    ('Neutral Grip Pull-Up'),
    ('Inverted Row'),
    ('Handstand Push-Up'),
    ('Pike Push-Up'),
    ('Bench Dips'),
    ('Bodyweight Air Squat'),
    ('Bodyweight Walking Lunge'),
    ('Pistol Squat'),
    ('Nordic Hamstring Curl'),
    ('Glute Bridge'),
    ('Bodyweight Standing Calf Raise'),
    ('Hanging Leg Raise'),
    ('Hanging Knee Raise'),
    ('Plank'),
    ('Side Plank'),
    ('Dead Bug'),
    ('Hollow Body Hold'),
    ('Bicycle Crunch'),
    ('Kettlebell Swing'),
    ('Kettlebell Goblet Squat'),
    ('Kettlebell Turkish Get-Up'),
    ('Kettlebell Clean And Press'),
    ('Kettlebell Snatch'),
    ('Single Arm Kettlebell Row'),
    ('Kettlebell Romanian Deadlift'),
    ('Kettlebell Overhead Press'),
    ('Kettlebell Windmill'),
    ('Kettlebell Cossack Squat'),
    ('Dual Kettlebell Deadlift'),
    ('Band Pull Apart'),
    ('Banded Lateral Walk'),
    ('Resistance Band Squat'),
    ('Resistance Band Push-Up'),
    ('Banded Pallof Press'),
    ('Resistance Band Row'),
    ('Banded Bicep Curl'),
    ('Banded Tricep Pushdown'),
    ('Band Assisted Pull-Up'),
    ('Banded Good Morning'),
    ('Smith Machine Bench Press'),
    ('Smith Machine Incline Press'),
    ('Smith Machine Squat'),
    ('Smith Machine Hip Thrust'),
    ('Smith Machine Bent Over Row'),
    ('Smith Machine Shoulder Press'),
    ('Smith Machine Calf Raise'),
    ('Smith Machine Shrug'),
    ('Ab Wheel Rollout'),
    ('Battle Ropes'),
    ('Jump Rope'),
    ('Medicine Ball Slam'),
    ('Sled Push'),
    ('Box Jumps')
)
DELETE FROM public.exercises
WHERE id IN (
  SELECT md5('m8:' || public.normalize_exercise_name(c.name))::uuid
  FROM csv_rows c
)
AND id NOT IN (SELECT exercise_id FROM public.sets WHERE exercise_id IS NOT NULL)
AND id NOT IN (SELECT exercise_id FROM public.template_exercises WHERE exercise_id IS NOT NULL);

-- Restore NULL equipment on backfilled rows
UPDATE public.exercises
SET equipment = NULL
WHERE id IN (SELECT exercise_id FROM public.catalog_seed_backfill);

DROP TABLE IF EXISTS public.catalog_seed_backfill;

NOTIFY pgrst, 'reload schema';
