-- Migration: 20260929010000_default_catalog_seed.sql
-- Description: M8 default catalog seed and equipment backfill (D-P7b-3, L48)
-- 1. Create tracking table public.catalog_seed_backfill(exercise_id uuid PK) with RLS enabled and no grants
-- 2. Backfill equipment ONLY on master exercises where equipment IS NULL and normalized names match CSV
-- 3. Insert curated master exercises with deterministic IDs md5('m8:' || normalize_exercise_name(name))::uuid,
--    skipping any name that normalizes-equal to ANY existing row (any owner, active or archived).

-- 1. Tracking table for backfilled rows
CREATE TABLE IF NOT EXISTS public.catalog_seed_backfill (
  exercise_id uuid PRIMARY KEY REFERENCES public.exercises(id) ON DELETE CASCADE
);

ALTER TABLE public.catalog_seed_backfill ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.catalog_seed_backfill FROM anon, authenticated;

-- 2. Backfill equipment on existing master rows with NULL equipment
WITH csv_rows(name, body_parts, equipment) AS (
  VALUES
    ('45 Degree Back Extension', ARRAY['Back', 'Legs']::text[], 'bodyweight'),
    ('Bicep cable pull', ARRAY['Biceps', 'Arms']::text[], 'cable'),
    ('Cable Lateral Raises', ARRAY['Shoulders']::text[], 'cable'),
    ('Dips', ARRAY['Chest', 'Triceps']::text[], 'bodyweight'),
    ('Dragon Flag', ARRAY['Core']::text[], 'bodyweight'),
    ('Dumbbell Lateral Raises', ARRAY['Shoulders']::text[], 'dumbbell'),
    ('Face Pulls', ARRAY['Shoulders', 'Back']::text[], 'cable'),
    ('Incline Bench Press', ARRAY['Chest', 'Triceps']::text[], 'barbell'),
    ('Inclined Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('L2H Cable Fly', ARRAY['Chest']::text[], 'cable'),
    ('Lat Cable Prayer', ARRAY['Back']::text[], 'cable'),
    ('Lat Pull Down', ARRAY['Back', 'Biceps']::text[], 'cable'),
    ('Leg Curl', ARRAY['Legs']::text[], 'machine'),
    ('Leg Extension Machine', ARRAY['Legs']::text[], 'machine'),
    ('Leg Raise', ARRAY['Core']::text[], 'bodyweight'),
    ('Overhead Tricep Cable Pull', ARRAY['Triceps', 'Arms']::text[], 'cable'),
    ('Preacher Curl', ARRAY['Biceps', 'Arms']::text[], 'barbell'),
    ('Rear delt crossover', ARRAY['Shoulders', 'Back']::text[], 'cable'),
    ('Reverse crunch', ARRAY['Core']::text[], 'bodyweight'),
    ('Seated Cable Row', ARRAY['Back', 'Biceps']::text[], 'cable'),
    ('Seated Chest Press', ARRAY['Chest', 'Triceps']::text[], 'machine'),
    ('Tricep Cable Pushdown', ARRAY['Triceps', 'Arms']::text[], 'cable'),
    ('Weighted Sit-Up', ARRAY['Core']::text[], 'other'),
    ('Bench Press', ARRAY['Chest', 'Triceps']::text[], 'barbell'),
    ('Romanian Deadlift', ARRAY['Legs', 'Back']::text[], 'barbell'),
    ('Zercher Squat', ARRAY['Legs', 'Core']::text[], 'barbell'),
    ('Overhead Press', ARRAY['Shoulders', 'Triceps']::text[], 'barbell'),
    ('Barbell Back Squat', ARRAY['Legs', 'Core']::text[], 'barbell'),
    ('Barbell Front Squat', ARRAY['Legs', 'Core']::text[], 'barbell'),
    ('Barbell Box Squat', ARRAY['Legs', 'Core']::text[], 'barbell'),
    ('Barbell Deadlift', ARRAY['Back', 'Legs']::text[], 'barbell'),
    ('Barbell Sumo Deadlift', ARRAY['Legs', 'Back']::text[], 'barbell'),
    ('Barbell Bent Over Row', ARRAY['Back', 'Biceps']::text[], 'barbell'),
    ('Pendlay Row', ARRAY['Back', 'Biceps']::text[], 'barbell'),
    ('Yates Row', ARRAY['Back', 'Biceps']::text[], 'barbell'),
    ('T-Bar Row', ARRAY['Back', 'Biceps']::text[], 'barbell'),
    ('Decline Bench Press', ARRAY['Chest', 'Triceps']::text[], 'barbell'),
    ('Close Grip Bench Press', ARRAY['Triceps', 'Chest']::text[], 'barbell'),
    ('Floor Press', ARRAY['Chest', 'Triceps']::text[], 'barbell'),
    ('Push Press', ARRAY['Shoulders', 'Triceps']::text[], 'barbell'),
    ('Behind The Neck Press', ARRAY['Shoulders', 'Triceps']::text[], 'barbell'),
    ('Barbell Upright Row', ARRAY['Shoulders', 'Back']::text[], 'barbell'),
    ('Barbell Shrug', ARRAY['Back', 'Shoulders']::text[], 'barbell'),
    ('Barbell Hip Thrust', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Good Morning', ARRAY['Back', 'Legs']::text[], 'barbell'),
    ('Barbell Walking Lunge', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Split Squat', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Hack Squat', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Standing Calf Raise', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'barbell'),
    ('EZ Bar Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'barbell'),
    ('Barbell Reverse Curl', ARRAY['Arms', 'Biceps']::text[], 'barbell'),
    ('Barbell Spider Curl', ARRAY['Biceps', 'Arms']::text[], 'barbell'),
    ('Barbell Skull Crusher', ARRAY['Triceps', 'Arms']::text[], 'barbell'),
    ('Overhead Barbell Tricep Extension', ARRAY['Triceps', 'Arms']::text[], 'barbell'),
    ('JM Press', ARRAY['Triceps', 'Chest']::text[], 'barbell'),
    ('Barbell Landmine Press', ARRAY['Chest', 'Shoulders']::text[], 'barbell'),
    ('Barbell Landmine Twist', ARRAY['Core']::text[], 'barbell'),
    ('Barbell Clean And Jerk', ARRAY['Full Body']::text[], 'barbell'),
    ('Barbell Snatch', ARRAY['Full Body']::text[], 'barbell'),
    ('Barbell Power Clean', ARRAY['Full Body']::text[], 'barbell'),
    ('Trap Bar Deadlift', ARRAY['Legs', 'Back']::text[], 'barbell'),
    ('Trap Bar Farmers Walk', ARRAY['Full Body', 'Back']::text[], 'barbell'),
    ('Dumbbell Bench Press', ARRAY['Chest', 'Triceps']::text[], 'dumbbell'),
    ('Incline Dumbbell Press', ARRAY['Chest', 'Triceps']::text[], 'dumbbell'),
    ('Decline Dumbbell Press', ARRAY['Chest', 'Triceps']::text[], 'dumbbell'),
    ('Dumbbell Chest Fly', ARRAY['Chest']::text[], 'dumbbell'),
    ('Incline Dumbbell Fly', ARRAY['Chest']::text[], 'dumbbell'),
    ('One Arm Dumbbell Row', ARRAY['Back', 'Biceps']::text[], 'dumbbell'),
    ('Chest Supported Dumbbell Row', ARRAY['Back', 'Biceps']::text[], 'dumbbell'),
    ('Dumbbell Pullover', ARRAY['Back', 'Chest']::text[], 'dumbbell'),
    ('Dumbbell Shrug', ARRAY['Back', 'Shoulders']::text[], 'dumbbell'),
    ('Dumbbell Romanian Deadlift', ARRAY['Legs', 'Back']::text[], 'dumbbell'),
    ('Dumbbell Goblet Squat', ARRAY['Legs', 'Core']::text[], 'dumbbell'),
    ('Dumbbell Bulgarian Split Squat', ARRAY['Legs']::text[], 'dumbbell'),
    ('Dumbbell Walking Lunge', ARRAY['Legs']::text[], 'dumbbell'),
    ('Dumbbell Step-Up', ARRAY['Legs']::text[], 'dumbbell'),
    ('Dumbbell Standing Calf Raise', ARRAY['Legs']::text[], 'dumbbell'),
    ('Dumbbell Sumo Squat', ARRAY['Legs']::text[], 'dumbbell'),
    ('Seated Dumbbell Shoulder Press', ARRAY['Shoulders', 'Triceps']::text[], 'dumbbell'),
    ('Arnold Press', ARRAY['Shoulders', 'Triceps']::text[], 'dumbbell'),
    ('Standing Dumbbell Shoulder Press', ARRAY['Shoulders', 'Triceps']::text[], 'dumbbell'),
    ('Dumbbell Front Raise', ARRAY['Shoulders']::text[], 'dumbbell'),
    ('Dumbbell Rear Delt Fly', ARRAY['Shoulders', 'Back']::text[], 'dumbbell'),
    ('Dumbbell Upright Row', ARRAY['Shoulders', 'Back']::text[], 'dumbbell'),
    ('Incline Dumbbell Rear Delt Raise', ARRAY['Shoulders', 'Back']::text[], 'dumbbell'),
    ('Dumbbell Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Hammer Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Concentration Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Spider Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Zottman Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Cross Body Hammer Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Overhead Dumbbell Tricep Extension', ARRAY['Triceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Skull Crusher', ARRAY['Triceps', 'Arms']::text[], 'dumbbell'),
    ('Single Arm Dumbbell Tricep Extension', ARRAY['Triceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Tricep Kickback', ARRAY['Triceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Side Bend', ARRAY['Core']::text[], 'dumbbell'),
    ('Dumbbell Snatch', ARRAY['Full Body']::text[], 'dumbbell'),
    ('Dumbbell Thruster', ARRAY['Full Body']::text[], 'dumbbell'),
    ('Dumbbell Clean And Press', ARRAY['Full Body']::text[], 'dumbbell'),
    ('Dumbbell Farmers Carry', ARRAY['Full Body', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Floor Press', ARRAY['Chest', 'Triceps']::text[], 'dumbbell'),
    ('Cable Crossover Fly', ARRAY['Chest']::text[], 'cable'),
    ('High To Low Cable Fly', ARRAY['Chest']::text[], 'cable'),
    ('Standing Cable Chest Press', ARRAY['Chest', 'Triceps']::text[], 'cable'),
    ('Single Arm Cable Row', ARRAY['Back', 'Biceps']::text[], 'cable'),
    ('Close Grip Cable Row', ARRAY['Back', 'Biceps']::text[], 'cable'),
    ('Single Arm Cable Lateral Raise', ARRAY['Shoulders']::text[], 'cable'),
    ('Cable Front Raise', ARRAY['Shoulders']::text[], 'cable'),
    ('Cable Upright Row', ARRAY['Shoulders', 'Back']::text[], 'cable'),
    ('Cable Hammer Curl', ARRAY['Biceps', 'Arms']::text[], 'cable'),
    ('High Cable Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'cable'),
    ('Cable Tricep Kickback', ARRAY['Triceps', 'Arms']::text[], 'cable'),
    ('Cable Crunch', ARRAY['Core']::text[], 'cable'),
    ('Cable Pull Through', ARRAY['Legs', 'Back']::text[], 'cable'),
    ('Incline Chest Press Machine', ARRAY['Chest', 'Triceps']::text[], 'machine'),
    ('Decline Chest Press Machine', ARRAY['Chest', 'Triceps']::text[], 'machine'),
    ('Pec Deck Fly', ARRAY['Chest']::text[], 'machine'),
    ('Machine Chest Fly', ARRAY['Chest']::text[], 'machine'),
    ('Chest Supported Row Machine', ARRAY['Back', 'Biceps']::text[], 'machine'),
    ('Seated Machine Row', ARRAY['Back', 'Biceps']::text[], 'machine'),
    ('Iso-Lateral High Row Machine', ARRAY['Back', 'Biceps']::text[], 'machine'),
    ('Assisted Pull-Up Machine', ARRAY['Back', 'Biceps']::text[], 'machine'),
    ('Assisted Dip Machine', ARRAY['Triceps', 'Chest']::text[], 'machine'),
    ('Machine Shrug', ARRAY['Back', 'Shoulders']::text[], 'machine'),
    ('Leg Press Machine', ARRAY['Legs']::text[], 'machine'),
    ('Hack Squat Machine', ARRAY['Legs']::text[], 'machine'),
    ('Pendulum Squat Machine', ARRAY['Legs']::text[], 'machine'),
    ('Belt Squat Machine', ARRAY['Legs']::text[], 'machine'),
    ('Seated Calf Raise Machine', ARRAY['Legs']::text[], 'machine'),
    ('Standing Calf Raise Machine', ARRAY['Legs']::text[], 'machine'),
    ('Hip Abduction Machine', ARRAY['Legs']::text[], 'machine'),
    ('Hip Adduction Machine', ARRAY['Legs']::text[], 'machine'),
    ('Overhead Shoulder Press Machine', ARRAY['Shoulders', 'Triceps']::text[], 'machine'),
    ('Lateral Raise Machine', ARRAY['Shoulders']::text[], 'machine'),
    ('Reverse Pec Deck Machine', ARRAY['Shoulders', 'Back']::text[], 'machine'),
    ('Bicep Curl Machine', ARRAY['Biceps', 'Arms']::text[], 'machine'),
    ('Tricep Extension Machine', ARRAY['Triceps', 'Arms']::text[], 'machine'),
    ('Abdominal Crunch Machine', ARRAY['Core']::text[], 'machine'),
    ('Reverse Hyperextension Machine', ARRAY['Back', 'Legs']::text[], 'machine'),
    ('Treadmill Running', ARRAY['Cardio']::text[], 'machine'),
    ('Stationary Bike', ARRAY['Cardio']::text[], 'machine'),
    ('Rowing Machine', ARRAY['Cardio', 'Back']::text[], 'machine'),
    ('Stair Climber', ARRAY['Cardio', 'Legs']::text[], 'machine'),
    ('Elliptical Trainer', ARRAY['Cardio']::text[], 'machine'),
    ('SkiErg', ARRAY['Cardio', 'Back']::text[], 'machine'),
    ('Assault Bike', ARRAY['Cardio', 'Full Body']::text[], 'machine'),
    ('Rotary Torso Machine', ARRAY['Core']::text[], 'machine'),
    ('Sissy Squat Machine', ARRAY['Legs']::text[], 'machine'),
    ('Push-Up', ARRAY['Chest', 'Triceps']::text[], 'bodyweight'),
    ('Diamond Push-Up', ARRAY['Triceps', 'Chest']::text[], 'bodyweight'),
    ('Decline Push-Up', ARRAY['Chest', 'Triceps']::text[], 'bodyweight'),
    ('Incline Push-Up', ARRAY['Chest', 'Triceps']::text[], 'bodyweight'),
    ('Pull-Up', ARRAY['Back', 'Biceps']::text[], 'bodyweight'),
    ('Chin-Up', ARRAY['Back', 'Biceps']::text[], 'bodyweight'),
    ('Neutral Grip Pull-Up', ARRAY['Back', 'Biceps']::text[], 'bodyweight'),
    ('Inverted Row', ARRAY['Back', 'Biceps']::text[], 'bodyweight'),
    ('Handstand Push-Up', ARRAY['Shoulders', 'Triceps']::text[], 'bodyweight'),
    ('Pike Push-Up', ARRAY['Shoulders', 'Triceps']::text[], 'bodyweight'),
    ('Bench Dips', ARRAY['Triceps', 'Chest']::text[], 'bodyweight'),
    ('Bodyweight Air Squat', ARRAY['Legs']::text[], 'bodyweight'),
    ('Bodyweight Walking Lunge', ARRAY['Legs']::text[], 'bodyweight'),
    ('Pistol Squat', ARRAY['Legs', 'Core']::text[], 'bodyweight'),
    ('Nordic Hamstring Curl', ARRAY['Legs']::text[], 'bodyweight'),
    ('Glute Bridge', ARRAY['Legs']::text[], 'bodyweight'),
    ('Bodyweight Standing Calf Raise', ARRAY['Legs']::text[], 'bodyweight'),
    ('Hanging Leg Raise', ARRAY['Core']::text[], 'bodyweight'),
    ('Hanging Knee Raise', ARRAY['Core']::text[], 'bodyweight'),
    ('Plank', ARRAY['Core']::text[], 'bodyweight'),
    ('Side Plank', ARRAY['Core']::text[], 'bodyweight'),
    ('Dead Bug', ARRAY['Core']::text[], 'bodyweight'),
    ('Hollow Body Hold', ARRAY['Core']::text[], 'bodyweight'),
    ('Bicycle Crunch', ARRAY['Core']::text[], 'bodyweight'),
    ('Kettlebell Swing', ARRAY['Back', 'Legs']::text[], 'kettlebell'),
    ('Kettlebell Goblet Squat', ARRAY['Legs', 'Core']::text[], 'kettlebell'),
    ('Kettlebell Turkish Get-Up', ARRAY['Full Body']::text[], 'kettlebell'),
    ('Kettlebell Clean And Press', ARRAY['Shoulders', 'Full Body']::text[], 'kettlebell'),
    ('Kettlebell Snatch', ARRAY['Full Body']::text[], 'kettlebell'),
    ('Single Arm Kettlebell Row', ARRAY['Back', 'Biceps']::text[], 'kettlebell'),
    ('Kettlebell Romanian Deadlift', ARRAY['Legs', 'Back']::text[], 'kettlebell'),
    ('Kettlebell Overhead Press', ARRAY['Shoulders', 'Triceps']::text[], 'kettlebell'),
    ('Kettlebell Windmill', ARRAY['Core', 'Shoulders']::text[], 'kettlebell'),
    ('Kettlebell Cossack Squat', ARRAY['Legs']::text[], 'kettlebell'),
    ('Dual Kettlebell Deadlift', ARRAY['Back', 'Legs']::text[], 'kettlebell'),
    ('Band Pull Apart', ARRAY['Back', 'Shoulders']::text[], 'band'),
    ('Banded Lateral Walk', ARRAY['Legs']::text[], 'band'),
    ('Resistance Band Squat', ARRAY['Legs']::text[], 'band'),
    ('Resistance Band Push-Up', ARRAY['Chest', 'Triceps']::text[], 'band'),
    ('Banded Pallof Press', ARRAY['Core']::text[], 'band'),
    ('Resistance Band Row', ARRAY['Back', 'Biceps']::text[], 'band'),
    ('Banded Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'band'),
    ('Banded Tricep Pushdown', ARRAY['Triceps', 'Arms']::text[], 'band'),
    ('Band Assisted Pull-Up', ARRAY['Back', 'Biceps']::text[], 'band'),
    ('Banded Good Morning', ARRAY['Back', 'Legs']::text[], 'band'),
    ('Smith Machine Bench Press', ARRAY['Chest', 'Triceps']::text[], 'smith'),
    ('Smith Machine Incline Press', ARRAY['Chest', 'Triceps']::text[], 'smith'),
    ('Smith Machine Squat', ARRAY['Legs']::text[], 'smith'),
    ('Smith Machine Hip Thrust', ARRAY['Legs']::text[], 'smith'),
    ('Smith Machine Bent Over Row', ARRAY['Back', 'Biceps']::text[], 'smith'),
    ('Smith Machine Shoulder Press', ARRAY['Shoulders', 'Triceps']::text[], 'smith'),
    ('Smith Machine Calf Raise', ARRAY['Legs']::text[], 'smith'),
    ('Smith Machine Shrug', ARRAY['Back', 'Shoulders']::text[], 'smith'),
    ('Ab Wheel Rollout', ARRAY['Core']::text[], 'other'),
    ('Battle Ropes', ARRAY['Cardio', 'Full Body']::text[], 'other'),
    ('Jump Rope', ARRAY['Cardio']::text[], 'other'),
    ('Medicine Ball Slam', ARRAY['Full Body']::text[], 'other'),
    ('Sled Push', ARRAY['Legs', 'Cardio']::text[], 'other'),
    ('Box Jumps', ARRAY['Legs', 'Cardio']::text[], 'other')
),
updated_rows AS (
  UPDATE public.exercises e
  SET equipment = c.equipment
  FROM csv_rows c
  WHERE e.is_master = true
    AND e.equipment IS NULL
    AND public.normalize_exercise_name(e.name) = public.normalize_exercise_name(c.name)
  RETURNING e.id
)
INSERT INTO public.catalog_seed_backfill (exercise_id)
SELECT id FROM updated_rows
ON CONFLICT (exercise_id) DO NOTHING;

-- 3. Insert curated master defaults with deterministic IDs
WITH csv_rows(name, body_parts, equipment) AS (
  VALUES
    ('45 Degree Back Extension', ARRAY['Back', 'Legs']::text[], 'bodyweight'),
    ('Bicep cable pull', ARRAY['Biceps', 'Arms']::text[], 'cable'),
    ('Cable Lateral Raises', ARRAY['Shoulders']::text[], 'cable'),
    ('Dips', ARRAY['Chest', 'Triceps']::text[], 'bodyweight'),
    ('Dragon Flag', ARRAY['Core']::text[], 'bodyweight'),
    ('Dumbbell Lateral Raises', ARRAY['Shoulders']::text[], 'dumbbell'),
    ('Face Pulls', ARRAY['Shoulders', 'Back']::text[], 'cable'),
    ('Incline Bench Press', ARRAY['Chest', 'Triceps']::text[], 'barbell'),
    ('Inclined Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('L2H Cable Fly', ARRAY['Chest']::text[], 'cable'),
    ('Lat Cable Prayer', ARRAY['Back']::text[], 'cable'),
    ('Lat Pull Down', ARRAY['Back', 'Biceps']::text[], 'cable'),
    ('Leg Curl', ARRAY['Legs']::text[], 'machine'),
    ('Leg Extension Machine', ARRAY['Legs']::text[], 'machine'),
    ('Leg Raise', ARRAY['Core']::text[], 'bodyweight'),
    ('Overhead Tricep Cable Pull', ARRAY['Triceps', 'Arms']::text[], 'cable'),
    ('Preacher Curl', ARRAY['Biceps', 'Arms']::text[], 'barbell'),
    ('Rear delt crossover', ARRAY['Shoulders', 'Back']::text[], 'cable'),
    ('Reverse crunch', ARRAY['Core']::text[], 'bodyweight'),
    ('Seated Cable Row', ARRAY['Back', 'Biceps']::text[], 'cable'),
    ('Seated Chest Press', ARRAY['Chest', 'Triceps']::text[], 'machine'),
    ('Tricep Cable Pushdown', ARRAY['Triceps', 'Arms']::text[], 'cable'),
    ('Weighted Sit-Up', ARRAY['Core']::text[], 'other'),
    ('Bench Press', ARRAY['Chest', 'Triceps']::text[], 'barbell'),
    ('Romanian Deadlift', ARRAY['Legs', 'Back']::text[], 'barbell'),
    ('Zercher Squat', ARRAY['Legs', 'Core']::text[], 'barbell'),
    ('Overhead Press', ARRAY['Shoulders', 'Triceps']::text[], 'barbell'),
    ('Barbell Back Squat', ARRAY['Legs', 'Core']::text[], 'barbell'),
    ('Barbell Front Squat', ARRAY['Legs', 'Core']::text[], 'barbell'),
    ('Barbell Box Squat', ARRAY['Legs', 'Core']::text[], 'barbell'),
    ('Barbell Deadlift', ARRAY['Back', 'Legs']::text[], 'barbell'),
    ('Barbell Sumo Deadlift', ARRAY['Legs', 'Back']::text[], 'barbell'),
    ('Barbell Bent Over Row', ARRAY['Back', 'Biceps']::text[], 'barbell'),
    ('Pendlay Row', ARRAY['Back', 'Biceps']::text[], 'barbell'),
    ('Yates Row', ARRAY['Back', 'Biceps']::text[], 'barbell'),
    ('T-Bar Row', ARRAY['Back', 'Biceps']::text[], 'barbell'),
    ('Decline Bench Press', ARRAY['Chest', 'Triceps']::text[], 'barbell'),
    ('Close Grip Bench Press', ARRAY['Triceps', 'Chest']::text[], 'barbell'),
    ('Floor Press', ARRAY['Chest', 'Triceps']::text[], 'barbell'),
    ('Push Press', ARRAY['Shoulders', 'Triceps']::text[], 'barbell'),
    ('Behind The Neck Press', ARRAY['Shoulders', 'Triceps']::text[], 'barbell'),
    ('Barbell Upright Row', ARRAY['Shoulders', 'Back']::text[], 'barbell'),
    ('Barbell Shrug', ARRAY['Back', 'Shoulders']::text[], 'barbell'),
    ('Barbell Hip Thrust', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Good Morning', ARRAY['Back', 'Legs']::text[], 'barbell'),
    ('Barbell Walking Lunge', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Split Squat', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Hack Squat', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Standing Calf Raise', ARRAY['Legs']::text[], 'barbell'),
    ('Barbell Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'barbell'),
    ('EZ Bar Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'barbell'),
    ('Barbell Reverse Curl', ARRAY['Arms', 'Biceps']::text[], 'barbell'),
    ('Barbell Spider Curl', ARRAY['Biceps', 'Arms']::text[], 'barbell'),
    ('Barbell Skull Crusher', ARRAY['Triceps', 'Arms']::text[], 'barbell'),
    ('Overhead Barbell Tricep Extension', ARRAY['Triceps', 'Arms']::text[], 'barbell'),
    ('JM Press', ARRAY['Triceps', 'Chest']::text[], 'barbell'),
    ('Barbell Landmine Press', ARRAY['Chest', 'Shoulders']::text[], 'barbell'),
    ('Barbell Landmine Twist', ARRAY['Core']::text[], 'barbell'),
    ('Barbell Clean And Jerk', ARRAY['Full Body']::text[], 'barbell'),
    ('Barbell Snatch', ARRAY['Full Body']::text[], 'barbell'),
    ('Barbell Power Clean', ARRAY['Full Body']::text[], 'barbell'),
    ('Trap Bar Deadlift', ARRAY['Legs', 'Back']::text[], 'barbell'),
    ('Trap Bar Farmers Walk', ARRAY['Full Body', 'Back']::text[], 'barbell'),
    ('Dumbbell Bench Press', ARRAY['Chest', 'Triceps']::text[], 'dumbbell'),
    ('Incline Dumbbell Press', ARRAY['Chest', 'Triceps']::text[], 'dumbbell'),
    ('Decline Dumbbell Press', ARRAY['Chest', 'Triceps']::text[], 'dumbbell'),
    ('Dumbbell Chest Fly', ARRAY['Chest']::text[], 'dumbbell'),
    ('Incline Dumbbell Fly', ARRAY['Chest']::text[], 'dumbbell'),
    ('One Arm Dumbbell Row', ARRAY['Back', 'Biceps']::text[], 'dumbbell'),
    ('Chest Supported Dumbbell Row', ARRAY['Back', 'Biceps']::text[], 'dumbbell'),
    ('Dumbbell Pullover', ARRAY['Back', 'Chest']::text[], 'dumbbell'),
    ('Dumbbell Shrug', ARRAY['Back', 'Shoulders']::text[], 'dumbbell'),
    ('Dumbbell Romanian Deadlift', ARRAY['Legs', 'Back']::text[], 'dumbbell'),
    ('Dumbbell Goblet Squat', ARRAY['Legs', 'Core']::text[], 'dumbbell'),
    ('Dumbbell Bulgarian Split Squat', ARRAY['Legs']::text[], 'dumbbell'),
    ('Dumbbell Walking Lunge', ARRAY['Legs']::text[], 'dumbbell'),
    ('Dumbbell Step-Up', ARRAY['Legs']::text[], 'dumbbell'),
    ('Dumbbell Standing Calf Raise', ARRAY['Legs']::text[], 'dumbbell'),
    ('Dumbbell Sumo Squat', ARRAY['Legs']::text[], 'dumbbell'),
    ('Seated Dumbbell Shoulder Press', ARRAY['Shoulders', 'Triceps']::text[], 'dumbbell'),
    ('Arnold Press', ARRAY['Shoulders', 'Triceps']::text[], 'dumbbell'),
    ('Standing Dumbbell Shoulder Press', ARRAY['Shoulders', 'Triceps']::text[], 'dumbbell'),
    ('Dumbbell Front Raise', ARRAY['Shoulders']::text[], 'dumbbell'),
    ('Dumbbell Rear Delt Fly', ARRAY['Shoulders', 'Back']::text[], 'dumbbell'),
    ('Dumbbell Upright Row', ARRAY['Shoulders', 'Back']::text[], 'dumbbell'),
    ('Incline Dumbbell Rear Delt Raise', ARRAY['Shoulders', 'Back']::text[], 'dumbbell'),
    ('Dumbbell Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Hammer Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Concentration Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Spider Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Zottman Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Cross Body Hammer Curl', ARRAY['Biceps', 'Arms']::text[], 'dumbbell'),
    ('Overhead Dumbbell Tricep Extension', ARRAY['Triceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Skull Crusher', ARRAY['Triceps', 'Arms']::text[], 'dumbbell'),
    ('Single Arm Dumbbell Tricep Extension', ARRAY['Triceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Tricep Kickback', ARRAY['Triceps', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Side Bend', ARRAY['Core']::text[], 'dumbbell'),
    ('Dumbbell Snatch', ARRAY['Full Body']::text[], 'dumbbell'),
    ('Dumbbell Thruster', ARRAY['Full Body']::text[], 'dumbbell'),
    ('Dumbbell Clean And Press', ARRAY['Full Body']::text[], 'dumbbell'),
    ('Dumbbell Farmers Carry', ARRAY['Full Body', 'Arms']::text[], 'dumbbell'),
    ('Dumbbell Floor Press', ARRAY['Chest', 'Triceps']::text[], 'dumbbell'),
    ('Cable Crossover Fly', ARRAY['Chest']::text[], 'cable'),
    ('High To Low Cable Fly', ARRAY['Chest']::text[], 'cable'),
    ('Standing Cable Chest Press', ARRAY['Chest', 'Triceps']::text[], 'cable'),
    ('Single Arm Cable Row', ARRAY['Back', 'Biceps']::text[], 'cable'),
    ('Close Grip Cable Row', ARRAY['Back', 'Biceps']::text[], 'cable'),
    ('Single Arm Cable Lateral Raise', ARRAY['Shoulders']::text[], 'cable'),
    ('Cable Front Raise', ARRAY['Shoulders']::text[], 'cable'),
    ('Cable Upright Row', ARRAY['Shoulders', 'Back']::text[], 'cable'),
    ('Cable Hammer Curl', ARRAY['Biceps', 'Arms']::text[], 'cable'),
    ('High Cable Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'cable'),
    ('Cable Tricep Kickback', ARRAY['Triceps', 'Arms']::text[], 'cable'),
    ('Cable Crunch', ARRAY['Core']::text[], 'cable'),
    ('Cable Pull Through', ARRAY['Legs', 'Back']::text[], 'cable'),
    ('Incline Chest Press Machine', ARRAY['Chest', 'Triceps']::text[], 'machine'),
    ('Decline Chest Press Machine', ARRAY['Chest', 'Triceps']::text[], 'machine'),
    ('Pec Deck Fly', ARRAY['Chest']::text[], 'machine'),
    ('Machine Chest Fly', ARRAY['Chest']::text[], 'machine'),
    ('Chest Supported Row Machine', ARRAY['Back', 'Biceps']::text[], 'machine'),
    ('Seated Machine Row', ARRAY['Back', 'Biceps']::text[], 'machine'),
    ('Iso-Lateral High Row Machine', ARRAY['Back', 'Biceps']::text[], 'machine'),
    ('Assisted Pull-Up Machine', ARRAY['Back', 'Biceps']::text[], 'machine'),
    ('Assisted Dip Machine', ARRAY['Triceps', 'Chest']::text[], 'machine'),
    ('Machine Shrug', ARRAY['Back', 'Shoulders']::text[], 'machine'),
    ('Leg Press Machine', ARRAY['Legs']::text[], 'machine'),
    ('Hack Squat Machine', ARRAY['Legs']::text[], 'machine'),
    ('Pendulum Squat Machine', ARRAY['Legs']::text[], 'machine'),
    ('Belt Squat Machine', ARRAY['Legs']::text[], 'machine'),
    ('Seated Calf Raise Machine', ARRAY['Legs']::text[], 'machine'),
    ('Standing Calf Raise Machine', ARRAY['Legs']::text[], 'machine'),
    ('Hip Abduction Machine', ARRAY['Legs']::text[], 'machine'),
    ('Hip Adduction Machine', ARRAY['Legs']::text[], 'machine'),
    ('Overhead Shoulder Press Machine', ARRAY['Shoulders', 'Triceps']::text[], 'machine'),
    ('Lateral Raise Machine', ARRAY['Shoulders']::text[], 'machine'),
    ('Reverse Pec Deck Machine', ARRAY['Shoulders', 'Back']::text[], 'machine'),
    ('Bicep Curl Machine', ARRAY['Biceps', 'Arms']::text[], 'machine'),
    ('Tricep Extension Machine', ARRAY['Triceps', 'Arms']::text[], 'machine'),
    ('Abdominal Crunch Machine', ARRAY['Core']::text[], 'machine'),
    ('Reverse Hyperextension Machine', ARRAY['Back', 'Legs']::text[], 'machine'),
    ('Treadmill Running', ARRAY['Cardio']::text[], 'machine'),
    ('Stationary Bike', ARRAY['Cardio']::text[], 'machine'),
    ('Rowing Machine', ARRAY['Cardio', 'Back']::text[], 'machine'),
    ('Stair Climber', ARRAY['Cardio', 'Legs']::text[], 'machine'),
    ('Elliptical Trainer', ARRAY['Cardio']::text[], 'machine'),
    ('SkiErg', ARRAY['Cardio', 'Back']::text[], 'machine'),
    ('Assault Bike', ARRAY['Cardio', 'Full Body']::text[], 'machine'),
    ('Rotary Torso Machine', ARRAY['Core']::text[], 'machine'),
    ('Sissy Squat Machine', ARRAY['Legs']::text[], 'machine'),
    ('Push-Up', ARRAY['Chest', 'Triceps']::text[], 'bodyweight'),
    ('Diamond Push-Up', ARRAY['Triceps', 'Chest']::text[], 'bodyweight'),
    ('Decline Push-Up', ARRAY['Chest', 'Triceps']::text[], 'bodyweight'),
    ('Incline Push-Up', ARRAY['Chest', 'Triceps']::text[], 'bodyweight'),
    ('Pull-Up', ARRAY['Back', 'Biceps']::text[], 'bodyweight'),
    ('Chin-Up', ARRAY['Back', 'Biceps']::text[], 'bodyweight'),
    ('Neutral Grip Pull-Up', ARRAY['Back', 'Biceps']::text[], 'bodyweight'),
    ('Inverted Row', ARRAY['Back', 'Biceps']::text[], 'bodyweight'),
    ('Handstand Push-Up', ARRAY['Shoulders', 'Triceps']::text[], 'bodyweight'),
    ('Pike Push-Up', ARRAY['Shoulders', 'Triceps']::text[], 'bodyweight'),
    ('Bench Dips', ARRAY['Triceps', 'Chest']::text[], 'bodyweight'),
    ('Bodyweight Air Squat', ARRAY['Legs']::text[], 'bodyweight'),
    ('Bodyweight Walking Lunge', ARRAY['Legs']::text[], 'bodyweight'),
    ('Pistol Squat', ARRAY['Legs', 'Core']::text[], 'bodyweight'),
    ('Nordic Hamstring Curl', ARRAY['Legs']::text[], 'bodyweight'),
    ('Glute Bridge', ARRAY['Legs']::text[], 'bodyweight'),
    ('Bodyweight Standing Calf Raise', ARRAY['Legs']::text[], 'bodyweight'),
    ('Hanging Leg Raise', ARRAY['Core']::text[], 'bodyweight'),
    ('Hanging Knee Raise', ARRAY['Core']::text[], 'bodyweight'),
    ('Plank', ARRAY['Core']::text[], 'bodyweight'),
    ('Side Plank', ARRAY['Core']::text[], 'bodyweight'),
    ('Dead Bug', ARRAY['Core']::text[], 'bodyweight'),
    ('Hollow Body Hold', ARRAY['Core']::text[], 'bodyweight'),
    ('Bicycle Crunch', ARRAY['Core']::text[], 'bodyweight'),
    ('Kettlebell Swing', ARRAY['Back', 'Legs']::text[], 'kettlebell'),
    ('Kettlebell Goblet Squat', ARRAY['Legs', 'Core']::text[], 'kettlebell'),
    ('Kettlebell Turkish Get-Up', ARRAY['Full Body']::text[], 'kettlebell'),
    ('Kettlebell Clean And Press', ARRAY['Shoulders', 'Full Body']::text[], 'kettlebell'),
    ('Kettlebell Snatch', ARRAY['Full Body']::text[], 'kettlebell'),
    ('Single Arm Kettlebell Row', ARRAY['Back', 'Biceps']::text[], 'kettlebell'),
    ('Kettlebell Romanian Deadlift', ARRAY['Legs', 'Back']::text[], 'kettlebell'),
    ('Kettlebell Overhead Press', ARRAY['Shoulders', 'Triceps']::text[], 'kettlebell'),
    ('Kettlebell Windmill', ARRAY['Core', 'Shoulders']::text[], 'kettlebell'),
    ('Kettlebell Cossack Squat', ARRAY['Legs']::text[], 'kettlebell'),
    ('Dual Kettlebell Deadlift', ARRAY['Back', 'Legs']::text[], 'kettlebell'),
    ('Band Pull Apart', ARRAY['Back', 'Shoulders']::text[], 'band'),
    ('Banded Lateral Walk', ARRAY['Legs']::text[], 'band'),
    ('Resistance Band Squat', ARRAY['Legs']::text[], 'band'),
    ('Resistance Band Push-Up', ARRAY['Chest', 'Triceps']::text[], 'band'),
    ('Banded Pallof Press', ARRAY['Core']::text[], 'band'),
    ('Resistance Band Row', ARRAY['Back', 'Biceps']::text[], 'band'),
    ('Banded Bicep Curl', ARRAY['Biceps', 'Arms']::text[], 'band'),
    ('Banded Tricep Pushdown', ARRAY['Triceps', 'Arms']::text[], 'band'),
    ('Band Assisted Pull-Up', ARRAY['Back', 'Biceps']::text[], 'band'),
    ('Banded Good Morning', ARRAY['Back', 'Legs']::text[], 'band'),
    ('Smith Machine Bench Press', ARRAY['Chest', 'Triceps']::text[], 'smith'),
    ('Smith Machine Incline Press', ARRAY['Chest', 'Triceps']::text[], 'smith'),
    ('Smith Machine Squat', ARRAY['Legs']::text[], 'smith'),
    ('Smith Machine Hip Thrust', ARRAY['Legs']::text[], 'smith'),
    ('Smith Machine Bent Over Row', ARRAY['Back', 'Biceps']::text[], 'smith'),
    ('Smith Machine Shoulder Press', ARRAY['Shoulders', 'Triceps']::text[], 'smith'),
    ('Smith Machine Calf Raise', ARRAY['Legs']::text[], 'smith'),
    ('Smith Machine Shrug', ARRAY['Back', 'Shoulders']::text[], 'smith'),
    ('Ab Wheel Rollout', ARRAY['Core']::text[], 'other'),
    ('Battle Ropes', ARRAY['Cardio', 'Full Body']::text[], 'other'),
    ('Jump Rope', ARRAY['Cardio']::text[], 'other'),
    ('Medicine Ball Slam', ARRAY['Full Body']::text[], 'other'),
    ('Sled Push', ARRAY['Legs', 'Cardio']::text[], 'other'),
    ('Box Jumps', ARRAY['Legs', 'Cardio']::text[], 'other')
)
INSERT INTO public.exercises (id, name, body_parts, body_part, equipment, is_master, user_id, is_archived)
SELECT
  md5('m8:' || public.normalize_exercise_name(c.name))::uuid,
  c.name,
  c.body_parts,
  array_to_string(c.body_parts, ', '),
  c.equipment,
  true,
  NULL,
  false
FROM csv_rows c
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e
  WHERE public.normalize_exercise_name(e.name) = public.normalize_exercise_name(c.name)
)
ON CONFLICT (id) DO NOTHING;

NOTIFY pgrst, 'reload schema';
